task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
 
  
  Sync_script:
      - git clone https://dumps.tadiphone.dev/dumps/oneplus/op535dl1.git
      - ls
      - cd op535dl1
      - ls 
      - cd 
      
      - python3 -m aospdtgen -o lineage-device-tree op535dl1
        Android device tree generator
        Version 0.1.0


