# .cirrus.yml

# Choose Ubuntu Linux platform
platform: linux



task:
  name: "Build Task"
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 16
      memory: 32G
        
  script:
       - echo "Running build with 16 CPUs"
       - # Add your build commands here


