# .cirrus.yml

# Choose Ubuntu Linux platform
platform: linux

# Choose Ubuntu image
image: ubuntu

# Allocate 16 CPUs
cpu: 16

# Define your build tasks
tasks:
  - name: Install sudo
    command: |
      apt-get update
      apt-get install sudo -y

