env:

    MANIFEST: https://github.com/PixelExperience/manifest -b thirteen

    DEVICE: CPH2381

    OEM: oneplus

    DT_LINK: https://github.com/ajaysinghsati/device_oneplus_CPH2381.git

    DT_PATH: device/$OEM/$DEVICE

    VT_LINK: 

    VT_PATH: 

    KT_LINK: https://github.com/OnePlus-sm6375-devices/android_kernel_oneplus_sm6375.git

    PLATFORM: sm6375

    KT_PATH: kernel/$OEM/$PLATFORM

    TARGET: bacon

    EXTRA_CMD: export SKIP_ABI_CHECKS=true

    LUNCH_COMBO: aosp_CPH2381-userdebug

    OUTPUT: PixelExperience*.zip

task:

  name: "Setting Up, Syncing, Building and Uploading..."

  timeout_in: 240m  

  container:

      image: ghcr.io/sushrut1101/docker:arch

      cpu: 8

      memory: 32G

  Storage-Checker_script:

      - df -h

      - lsblk

      - ls -l -a -h

  

  Sync_script:

      - echo "============================"

      - echo "Syncing The Sources..."

      - echo "============================"
      
      - cd ~/
      - git clone https://github.com/akhilnarang/scripts
      - cd scripts
      - ./setup/android_build_env.sh


      
      - echo "============================"

  Build_script:

      - echo "============================"

      - echo "Starting the Build..."

      - echo "============================"

      - mkdir -p ~/android/pe
      - export USE_CCACHE=1

      - export CCACHE_EXEC=/usr/bin/ccache

      - ccache -M 50G
      - cd ~/android/pe
      - repo init -u https://github.com/PixelExperience/manifest -b thirteen
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - source build/envsetup.sh

      - lunch aosp_merlinx-userdebug
      - croot

      - mka bacon -j$(nproc --all)



     

  Upload_script:

      - echo "============================"

      - echo "Uploading the Build..."

      - echo "============================"

      - cd ~/work

      - cd out/target/product/"$DEVICE"

      - ls -lh

      - pwd

      - chmod 777 *

      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "

      - echo " "

      - echo "============================"

      - echo "Build Uploaded!"

      - echo "Please see the link Below-  "

      - echo "----------------------------"

      - cat link.txt && echo " "

      - echo "============================"

        
